/*
 * generated by Xtext
 */
package de.lynorics.eclipse.jangaroo.ui.contentassist

import de.lynorics.eclipse.jangaroo.ui.contentassist.AbstractAS3ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AS3ProposalProvider extends AbstractAS3ProposalProvider {
}
