/*
* generated by Xtext
*/
package de.lynorics.eclipse.jangaroo.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.lynorics.eclipse.jangaroo.services.AS3GrammarAccess;

public class AS3Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AS3GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.lynorics.eclipse.jangaroo.parser.antlr.internal.InternalAS3Parser createParser(XtextTokenStream stream) {
		return new de.lynorics.eclipse.jangaroo.parser.antlr.internal.InternalAS3Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public AS3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AS3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
