/*
 * Copyright 2013
 *
 * Licensed under the Eclipse Public License version 1.0, available at
 * http://opensource.org/licenses/eclipse-1.0.txt
 */
/*
 * generated by Xtext
 */
package de.lynorics.eclipse.jangaroo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.outline.actions.IOutlineContribution;

import com.google.inject.Binder;
import com.google.inject.name.Names;

import de.lynorics.eclipse.jangaroo.ui.outline.FilterImportsOperationsContribution;
import de.lynorics.eclipse.jangaroo.ui.outline.FilterUsesOperationsContribution;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AS3UiModule extends de.lynorics.eclipse.jangaroo.ui.AbstractAS3UiModule {
	public AS3UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public void configureFilterOperationsContribution(Binder binder) {
		  binder
		    .bind(IOutlineContribution.class).annotatedWith(
		      Names.named("FilterImportsOperationsContribution"))
		    .to(FilterImportsOperationsContribution.class);
		  binder
		    .bind(IOutlineContribution.class).annotatedWith(
		      Names.named("FilterUsesOperationsContribution"))
		    .to(FilterUsesOperationsContribution.class);
		}

    public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
        return AS3EObjectHoverProvider.class;
    }
 
    public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProviderr() {
        return AS3EObjectDocumentationProvider.class;
    }
}
