/*
 * generated by Xtext
 */
package de.lynorics.eclipse.jangaroo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AS3RuntimeModule extends de.lynorics.eclipse.jangaroo.AbstractAS3RuntimeModule {

}
