/*
* generated by Xtext
*/
package de.lynorics.eclipse.jangaroo;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AS3StandaloneSetup extends AS3StandaloneSetupGenerated{

	public static void doSetup() {
		new AS3StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

