/*
* generated by Xtext
*/
package de.lynorics.eclipse.jangaroo;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AS3UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.lynorics.eclipse.jangaroo.ui.internal.AS3Activator.getInstance().getInjector("de.lynorics.eclipse.jangaroo.AS3");
	}
	
}
